name: report2html

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master
    - uses: nikeee/setup-pandoc@v1
    - run: cd docs/report & pandoc --output=index.html index.md
